### ISSUE TITLE
All function defined within a module using mproperty get the module argument

### ISSUE THREAD

**Issue by amaeldoe** [josiahcarlson/mprop#1]
Hi,

All function, not just the one marked with the mproperty decorator, get a module argument. As a result:

**\* test.py ***

<pre>
from mprop import mproperty

@mproperty
def TEST(mod):
        return "TEST"

def my_func():
        return "my_func"
</pre>

---

Python 2.7.10 (default, May 27 2015, 18:11:38) 
[GCC 5.1.1 20150422 (Red Hat 5.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import test
> > > test.TEST
> > > 'TEST'
> > > test.my_func()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: my_func() takes no arguments (1 given)

**Comment by rominf** [comment]
I have the same problem. The same applies to:
```
import mprop; mprop.init()
```

This makes package unusable.

@josiahcarlson, can you fix this?

**Comment by josiahcarlson** [comment]
Holy crap, sorry, didn't see this bug report until now. Otherwise I'd have fixed it. Will try to fix this weekend.

**Comment by josiahcarlson** [comment]
This should be fixed in the master branch, as well as in pypi mprop==0.15.0 .

Thank you for the bug report @amaeldoe and reminder @rominf !
