### ISSUE TITLE
_pmodule not found

### ISSUE THREAD

**Issue by CodingOctocat** [josiahcarlson/mprop#5]
i can't using _pmodule to access property in self module.

**Comment by josiahcarlson** [comment]
Can you show the code you are using?

Are you using Python 3.7+? Because there you can use normal deferred attributes, as per: https://peps.python.org/pep-0562/ , which should solve your problems more consistently.

**Comment by CodingOctocat** [comment]
I use Python 3.10，The code is the same as the [README.rst](https://github.com/josiahcarlson/mprop#readme).

**Comment by josiahcarlson** [comment]
You should not use this module, and should instead use Python 3.7+ and `__getattr__` as described https://peps.python.org/pep-0562/, and as linked in the first paragraph of https://github.com/josiahcarlson/mprop#readme .

To quote myself in the 2nd paragraph, "unless there is something major, this project is mostly for historical purposes".

**Comment by CodingOctocat** [comment]
You are right, I used methods instead of properties for convenience.
