### ISSUE TITLE
Python 3.12 compatibility - imp module deprecated

### ISSUE THREAD

**Issue by glenm-nz** [josiahcarlson/mprop#6]
Python 3.12 has deprecated the 'imp' module in favour of importlib. This results in the following error when importing mprop:

`Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mprop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/mqttany/mqttany/venv/lib/python3.12/site-packages/mprop.py", line 2, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'`

(Shown from the python console for clarity, but I am using https://github.com/CrazyIvan359/mqttany which also imports mprop)

In all honesty, I don't really know how the above program leverages mprop, but simply changing line 2 of mprop.py from:
`import imp`
to 
`import importlib`

allows mprop to load correctly:
`Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mprop
>>>`

This change obviously comes nowhere near being a regression tested change, but the above mentioned program which leverages mprop seems to work happily now.

**Comment by josiahcarlson** [comment]
Turns out we don't actually use the module. So I removed it. See 0.17.0 .

Thank you for the report.

**Comment by glenm-nz** [comment]
Perfect - Thanks for that - just installed the other program again, and this time it grabbed mprop 0.17.0 via pip  and finished the setup without issue
Cheers - Glen
